### ISSUE TITLE
Can't use non latin1 characters in basic auth

### ISSUE THREAD

**Issue by biern** [sloria/webtest-plus#3]
Hi!
I've tried to use webtest-plus with utf-8 encoded password and it fails, trying to encode that data to `latin1` first. 
As far as I understand basic auth, the point of encoding to base64 is to be able to pass any binary data as the value, so I'm not sure if `encode` / `decode` to latin1 step is necessary.  

```
username = 'John', password = '\xc5\xbc'

    def _basic_auth_str(username, password):
        """Returns a Basic Auth string."""
>       return 'Basic ' + b64encode(('%s:%s' % (username, password)).encode('latin1')).strip().decode('latin1')
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5: ordinal not in range(128)

/usr/local/lib/python2.7/site-packages/webtest_plus/app.py:13: UnicodeDecodeError

```

**Comment by sloria** [comment]
Thanks for reporting. I believe `_basic_auth_str` was originally taken from requests: https://github.com/kennethreitz/requests/blob/f8189eda10f1756b36717912b96ecdb5cafe625e/requests/auth.py#L28-L69 . It's likely that it needs to be updated. I would certainly review and merge a PR for this.
